name: Scraping de Anime en 3Cat (Manual)

# 'workflow_dispatch' activa el botón para ejecutarlo manualmente
on: 
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  scraper_job:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Copiar el repositorio de GitHub
      uses: actions/checkout@v4

    - name: 2. Configurar el entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 3. Instalar librerías de Scraping
      run: |
        pip install requests beautifulsoup4

    - name: 4. Ejecutar el script y mostrar lista
      run: python scraping_3cat.py
