name: Probar script joel.py

on: [push, workflow_dispatch]

# Esto soluciona la advertencia de Node.js en 2026
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python en Ubuntu
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Ejecutar joel.py
      run: python joel.py
