name: Probar script joel.py

# Se ejecuta automáticamente cada vez que subes cambios (push)
on: [push, workflow_dispatch]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python en Ubuntu
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Instala la última versión estable de Python

    # DESCOMENTA LAS SIGUIENTES LÍNEAS SI TU SCRIPT NECESITA LIBRERÍAS (requirements.txt)
    # - name: Instalar dependencias
    #   run: |
    #     pip install -r requirements.txt

    - name: Ejecutar joel.py
      run: python joel.py
